export enum ProductStateActionsTypes{
    GET_PRODUCTS = "GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAILURE= "GET_PRODUCTS_FAILURE",

    ADD_PRODUCTS= "ADD_PRODUCTS",
    ADD_PRODUCTS_SUCCESS= "ADD_PRODUCTS_SUCCESS",
    ADD_PRODUCTS_FAILURE= "ADD_PRODUCTS_FAILURE",

    UPDATE_PRODUCTS= "UPDATE_PRODUCTS",
    UPDATE_PRODUCTS_SUCCESS= "UPDATE_PRODUCTS_SUCCESS", 
    UPDATE_PRODUCTS_FAILURE= "UPDATE_PRODUCTS_FAILURE",

    DELETE_PRODUCTS= "DELETE_PRODUCTS",
    DELETE_PRODUCTS_SUCCESS= "DELETE_PRODUCTS_SUCCESS",
    DELETE_PRODUCTS_FAILURE= "DELETE_PRODUCTS_FAILURE",
}